### ISSUE TITLE
为什么使用konga设置range时一直不成功呢？

### ISSUE THREAD

**Issue by OliverYu949** [raoxiaoyan/kong-plugins-canary#1]

**Comment by WJC101** [comment]
> _No description provided._

解决了么？我也有同样的问题

**Comment by OliverYu949** [comment]
> > _No description provided._
> 
> 解决了么？我也有同样的问题

解决了，因为range是一个数组，输入后按回车键再提交才可以。

**Comment by WJC101** [comment]
> > > _No description provided._
> > 
> > 
> > 解决了么？我也有同样的问题
> 
> 解决了，因为range是一个数组，输入后按回车键再提交才可以。

OK  多谢  我也发现了
